server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 639789521908-b21em08tn4ielvu1oo0vahvbha90rrcf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1115449602932714
            client-secret: f3ce6c5ad97f984775d5c06a7edad48c
            scope:
              - email
              - public_profile

          naver:
            client-id: 1Vr22w6KLmQ1JAsPfTmB
            client-secret: BsJ4BiNXKg
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver



        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

